### ISSUE TITLE
Явно обозначить наличие специфичных элементов в `pasproj`

### ISSUE THREAD

**Issue by samuraiGH** [ForNeVeR/PascalABC.NET.SDK#25]
Для элемента `MainCompile` это можно сделать таким `.targets` файлом

```xml
<Project>
	<ItemGroup>
		<AvailableItemName Include="MainCompile" />
	</ItemGroup>
</Project>
```
В `pasproj`  нужно будет добавить
```xml
<Project>
	...

	<Import Project="path to targets file" />
</Project>
```
После этого можно например переключать Build Action в Visual Studio

Но я в `csproj` не наблюдаю таких строчек, по крайней мере в SDK-style проектах. Возможно этот файл можно подключить как-то неявно силами SDK

**Comment by ForNeVeR** [comment]
Кажется, это можно провто дописать в `Sdk.props`, вот сюда: https://github.com/ForNeVeR/PascalABC.NET.SDK/blob/92e31ded961e7de8ae921d7e475aff8a81d06caf/PascalABC.NET.SDK/Sdk/Sdk.props
